### ISSUE TITLE
Failed to decode json when there's a WARNING for the pgbackrest

### ISSUE THREAD

**Issue by manute** [pgstef/check_pgbackrest#32]
Hey @pgstef , 

Thank you for creating this project! It 's very useful! 

One thing I noticed is that if the `pgbackrest` info is throwing a WARNING before the results the decode json fails (I think is the line 540), ie: 

```shell
# check_pgbackrest -c /home/appuser/conf -S an -s retention -Ojson
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "WARN: configuration ...") at /usr/bin/check_pgbackrest line 540.
# pgbackrest info --stanza=an --output=json --log-level-console=error --config=/home/appuser/conf
WARN: configuration file contains invalid option 'repo1-s3-key-role
[{"archive":[{"database":{"id":1,"repo-key":1},"rest of the json string....}]
```

**Comment by pgstef** [comment]
Hi,

That's weird. What version are you using? In the current one, `--log-level-console=error` is passed to [pgbackrest info](https://github.com/pgstef/check_pgbackrest/blob/c5ef42f2daabc27653650960faac75e97682aef7/check_pgbackrest#L521) so warnings shouldn't be returned by pgBackRest.

Could you try adding `--debug` to see exactly what `pgbackrest info` command is used by check_pgbackrest?

**Comment by manute** [comment]
Yeah, the versions are :
```shell
> check_pgbackrest --version
check_pgbackrest version 2.2, Perl 5.30.0

> pgbackrest version
pgBackRest 2.38
```
And the issue is when the `pgbackrest.conf` contains an invalid option, so it seems that the WARNING appears even if the `--log-level-console=error` is passed: 
```shell
 > check_pgbackrest -c /home/appuser/bad.conf -S an -s retention -Ojson  --debug
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=an --output=json --log-level-console=error --config=/home/appuser/bad.conf'
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "WARN: configuration ...") at /usr/bin/check_pgbackrest line 540.
```
Executing the actual `pgbackrest info` cmd from the above msg: 
````shell 
> pgbackrest info --stanza=an --output=json --log-level-console=error --config=/home/appuser/bad.conf
WARN: configuration file contains invalid option 'repo1-s3-key-role'
[{"archive":[{"database":{"id":1,"repo-key":1},"id":"..... rest of the json"}]
```
Thanks!

**Comment by pgstef** [comment]
That behavior comes from [pgBackRest](https://github.com/pgbackrest/pgbackrest/blob/c98baab6b56967e222b825e22e5808e17c02d025/src/config/parse.c#L1638) itself to make sure config file warnings will be output.

We removed the ["WARN" filtering](https://github.com/pgstef/check_pgbackrest/commit/998c5658e8ef519b900a569e19e421e39d9ea6a2) previously because of various reported issues. So I'd prefer not to bring it back.

I kinda have mixed feelings about this "issue". I believe the best answer would be: _please, fix your pgBackRest configuration_.
In the sense that ignoring configuration errors might lead to point to inaccurate data without you knowing...

That being said, I agree the error message should be improved. Would it make sense to have this kind of output ?
```
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=mycluster --output=json --log-level-console=error'
pgBackRest output was not valid JSON.
HINT: does your configuration file contain invalid option?
```

Kind Regards

**Comment by pgstef** [comment]
I just [pushed](https://github.com/pgstef/check_pgbackrest/commit/2670af28808c3b3e2b7d32df48969b1a05504374) an update to catch the invalid json problem and display the HINT message.

You can directly try the dev release using the main branch script.

Hope this helps,
Kind Regards
